import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <header style={{padding: 16, borderBottom: '1px solid #eee'}}>
          <strong>Wiki Generator</strong>
        </header>
        <main style={{padding: 16}}>{children}</main>
      </body>
    </html>
  );
}
